backend:
  name: github
  repo: antidolgi/pravdavologda.rf

local_backend: false

media_folder: static/images
public_folder: /images

collections:
  - name: services
    label: Услуги
    folder: content/services
    create: true
    fields:
      - { name: title, label: Заголовок, widget: string }
      - { name: price, label: Цена, widget: number }
      - { name: description, label: Описание, widget: text }
      - { name: category, label: Категория, widget: select, options: ["Физические лица", "Бизнес"] }
