backend:
  name: github
  repo: antidolgi/pravdavologda.rf  # ← ЗАМЕНИТЕ на ваш GitHub логин и имя репозитория

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "services"
    label: "Услуги"
    folder: "content/services"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Цена (в рублях)", name: "price", widget: "number" }
      - { label: "Описание", name: "description", widget: "text" }
      - { label: "Категория", name: "category", widget: "select", options: ["Физические лица", "Бизнес"] }
